version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: subdomain-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: username #modifica username, password e MONGO_URI
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: ./app
    container_name: subdomain-app
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongo_uri #MODIFICA
      DATABASE_NAME: db_name #add_db_name
      COLLECTION_NAME: collection_name #add_collection_name
    volumes:
      - ./data:/app/data  # Monta la cartella locale nel container
    command: python subdomain_takeover_docker.py

volumes:
  mongodb_data:
